[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mzpy"
dynamic = ["version"]
description = "A pandas-like toolkit for MS data handling"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11"
authors = [{ name = "zq-lab", email = "zhangq@nwsuaf.edu.cn" }]
dependencies = [
    "igraph>=0.11",
    "numba>=0.57.1",
    "numpy>=1.25",
    "pandas>=2.2.1",
    "plotnine>=0.12",
    "pycairo>=1.28.0",
    "rdkit>=2023.9.5",
    "requests>=2.32",
    "scikit-learn>=1.6.0",
    "scipy>=1.10.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.4",
    "tqdm>=4.67.1",
    "werkzeug>=3.0"
]

[project.scripts]
mzpyW = "mzpy.webUI.cli:main"

[tool.setuptools.dynamic]
version = { attr = "mzpy.__version__" }

[tool.setuptools.packages.find]
where = ["."]



